# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/shorttimefly"
  weibo: "http://weibo.com/shorttime"
  #rss: "#"
  #facebook: "#"
  # google: "#"
  # twitter: "#"
  # linkedin: "#"

# rss: /atom.xml

# Content
excerpt_link: more
fancybox: true

# Miscellaneous

favicon: /favicon.png

#你的头像
avatar: "http://tp4.sinaimg.cn/1763706547/180/40018057459/1"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
#friends:
#奥巴马的博客: http://localhost:4000/
#卡卡的美丽传说: http://localhost:4000/
#本泽马的博客: http://localhost:4000/
#吉格斯的博客: http://localhost:4000/
#习大大大不同: http://localhost:4000/
#托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 你看那个人，好像一条狗啊。